site_name: ProteoLib

theme:
  name: null
  custom_dir: material
  palette:
    primary: blue grey

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true



  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  icon:
    logo: logo

extra:
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:anurag.igib@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/anuragraj/ProteoLib
  
#buttons
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details